"""``wagent skill {install,uninstall}`` — materialize the
verify-scenario skill into Claude Code's skill directory.

    wagent skill install         # write files into ~/.claude/skills/
    wagent skill uninstall       # remove the skill

The repo does NOT ship with a pre-populated ``.claude/skills/`` tree —
that directory belongs to each user's Claude Code home and the installed
copy needs to carry the absolute path of THIS checkout's ``wagent`` binary.
Generating at install time keeps a single source of truth (this module)
and lets the same repo be used from multiple machines or re-installed
after moving the checkout.

The install command rewrites the skill files on every run, so re-running
after ``git pull`` (or recreating the venv) is idempotent and always
produces absolute paths that still point at the right place.
"""

from __future__ import annotations

import argparse
import os
import shutil
import stat
import sys
from pathlib import Path
from textwrap import dedent

SKILL_NAME = "verify-scenario"

# Default install target — Claude Code's user-global skill home. The
# alternative (repo-local ``.claude/skills/``) was rejected because
# the operator needs to invoke the skill from other projects too.
DEFAULT_INSTALL_DIR = Path.home() / ".claude" / "skills"


# ───────────────────────────────────────────────────────────────────
# Path resolution
# ───────────────────────────────────────────────────────────────────


def _repo_root() -> Path:
    """Resolve the WebAgentFlow repo root from this module's location.

    This file lives at ``apps/cli/wagent/skill.py`` after the package
    refactor, so the repo root is four parents up. The ``WBAF_REPO``
    env var takes precedence for unusual install layouts.
    """
    override = os.environ.get("WBAF_REPO")
    if override:
        return Path(override).resolve()
    return Path(__file__).resolve().parent.parent.parent.parent


def _resolve_wagent_binary(repo_root: Path) -> Path:
    """Best-effort resolve the ``wagent`` binary path the skill should use.

    Priority:
      1. $WBAF_WAGENT env var (explicit override)
      2. <repo>/.venv/bin/wagent (standard dev setup)
      3. shutil.which('wagent') (system-wide install)

    Install DOESN'T fail when the binary is missing; it records the
    resolved path and warns. The shim itself fails fast at invocation
    with a clear error, so a missing binary is a recoverable state.
    """
    override = os.environ.get("WBAF_WAGENT")
    if override:
        return Path(override)
    venv_wagent = repo_root / ".venv" / "bin" / "wagent"
    if venv_wagent.exists():
        return venv_wagent
    from_path = shutil.which("wagent")
    if from_path:
        return Path(from_path)
    # Last resort: point at where it SHOULD be so the user gets a
    # coherent "missing at X, did you run pip install -e apps/cli?"
    # message from the shim.
    return venv_wagent


# ───────────────────────────────────────────────────────────────────
# Template for run.sh
# ───────────────────────────────────────────────────────────────────


def _shell_quote(value: str) -> str:
    """Minimal POSIX-shell quoting for a single argument."""
    if value and all(c.isalnum() or c in "-_./:@=" for c in value):
        return value
    escaped = value.replace("'", "'\\''")
    return f"'{escaped}'"


def _render_run_sh(wagent_path: Path, repo_root: Path) -> str:
    # The template is intentionally tiny — all the real logic lives
    # in ``wagent verify``. run.sh is just a shim that resolves the
    # right binary and forwards arguments.
    return dedent(
        f"""\
        #!/usr/bin/env bash
        # Generated by WebAgentFlow — wagent skill install
        # Re-run ``wagent skill install`` after moving the repo or
        # re-creating the venv — this file hard-codes absolute paths
        # so it can be invoked from any working directory.
        set -euo pipefail

        WBAF_REPO={_shell_quote(str(repo_root))}
        WBAF_WAGENT={_shell_quote(str(wagent_path))}

        if [[ ! -x "$WBAF_WAGENT" ]]; then
          echo "verify-scenario: wagent binary missing at $WBAF_WAGENT" >&2
          echo "  From $WBAF_REPO, run '.venv/bin/pip install -e apps/cli'" >&2
          echo "  then re-run 'wagent skill install'." >&2
          exit 2
        fi

        exec "$WBAF_WAGENT" verify "$@"
        """,
    )


# ───────────────────────────────────────────────────────────────────
# Template for SKILL.md
# ───────────────────────────────────────────────────────────────────


def _render_skill_md(run_sh: Path, repo_root: Path, api_base: str) -> str:
    # Reporting contract here mirrors CLAUDE.md's execution-boundary
    # section — edits must stay in sync.
    return dedent(
        f"""\
        ---
        name: {SKILL_NAME}
        description: >
          Run a WebAgentFlow autonomous exploration (spec-driven or
          ad-hoc URL) and return the project-internal Supervisor
          Agent's verdict and scorecard for analysis. The AI coding
          agent invokes this skill instead of running explorations
          itself.
        ---

        # verify-scenario

        Runs one autonomous exploration against a web page via the
        running WebAgentFlow API and prints the result JSON. The AI
        coding agent (you, Claude Code) invokes this skill when the
        user asks to verify a scenario, run a spec, check a workflow,
        or otherwise exercise the WebAgentFlow engine end-to-end.

        This skill was installed from `{repo_root}` — re-run
        `wagent skill install` from that checkout after a git pull
        so the pinned binary paths stay current.

        ## When to invoke

        Use this skill when the user's request implies a live run:
        "跑一下 X", "verify scenario Y", "check the users fixture",
        etc. Do NOT use this skill for tasks that don't need a real
        browser run:

        - Inspecting source code → use `Read` / `Grep`
        - Running unit tests → use pytest directly
        - Dry-running ideas without execution → discuss without
          invoking the skill

        ## How to invoke

        Call the shim with Bash. Pick one of the two shapes:

            # Spec-driven (the common case)
            {run_sh} --spec-id <spec> --scenario <scenario>

            # Ad-hoc URL
            {run_sh} --url <url>

        Useful arguments (full list via `{run_sh} --help`):

        - `--spec-id login --scenario valid_credentials` — run a
          persisted spec + scenario; URL and fill_values / toggle_values
          hydrate from the spec automatically.
        - `--url http://localhost:5175/users` — ad-hoc run.
        - `--fill-values '{{"username":"admin"}}'` — override text
          inputs (JSON object, or `@path.json`).
        - `--toggle-values '{{"status":"active"}}'` — override radio /
          checkbox (JSON object, or `@path.json`).
        - `--full` — emit full snapshot (page_analysis + all steps).
          Default is a trimmed summary; the full form is usually too
          large to read in one go. For deep inspection, ask the user
          to open the run by `run_id` in their WebAgentFlow console.
        - `--pretty` — indent the JSON for human reading.
        - `--api-base http://host:port` — point at a non-default API.

        ## Output contract

        - **stdout**: exactly one JSON object with `run_id`, `verdict`,
          `scenario_matched`, `summary`, `final_url`, `supervisor`, and
          `scorecard`. Safe to parse directly. The CLI is a backend
          client — it does NOT emit a frontend URL; the user knows
          where their console is.
        - **stderr**: a one-line banner (`✓/✗ verdict [scenario-*] —
          scorecard`) and any error text. Ignore when parsing stdout.
        - **exit 0**: scenario matched expectation (spec runs) OR
          verdict == `success` (ad-hoc runs).
        - **exit 1**: scenario mismatched expectation, OR verdict in
          {{`partial_success`, `failure`, `uncertain`}} for ad-hoc runs.
        - **exit 2**: CLI / network / spec error (the run did not happen).

        ## Reporting contract — MUST follow

        When reporting results back to the user, you MUST:

        1. Include `supervisor.verdict` and `supervisor.summary`
           verbatim — do not paraphrase the Supervisor Agent. Also
           note `supervisor.source` (`"llm"` = real LLM verdict;
           `"fallback"` + `supervisor.error_kind` = rule-mirrored
           because the LLM call failed — call the user's attention to
           this so they know the supervisor layer was bypassed).
        2. Include the 5 scorecard scores:
           `element_recognition`, `action_coverage`, `verdict_accuracy`,
           `distraction_avoidance`, `supervisor_agreement`. Cite the
           actual numbers.
        3. Include the `run_id` so the user can look the run up in
           their WebAgentFlow console (the CLI stays backend-only and
           does not fabricate a frontend URL).
        4. Interpret `scenario_matched` carefully. For spec runs:
           `true` means the run satisfied the scenario's declared
           expectation — report this as "scenario matched expectation"
           even when `verdict` is `failure` (e.g. `invalid_credentials`
           EXPECTS the login wall to persist). `false` means the run
           deviated from spec and is the real signal to dig into. Do
           NOT collapse "verdict=failure + scenario_matched=true" into
           "it failed" — that confuses a passing negative-path test
           with a broken positive-path test.
        5. If the verdict is not `success` AND `scenario_matched` is
           not `true`, read the step log + `supervisor.anomalies` +
           `supervisor.suggestions` and offer a concrete next step
           (e.g. "the radio selector didn't discriminate by value —
           would you like me to inspect the planner's matcher?").

        You MUST NOT:
        - Summarize as "passed" / "failed" without citing the verdict,
          scenario_matched, and score values from this run.
        - Fabricate verdicts or claim a run succeeded when the exit
          code was non-zero.
        - Re-run the skill in a loop to average results — each run
          costs real Playwright time + an LLM supervisor call.

        ## Prerequisites

        The WebAgentFlow API must be running at `{api_base}` (default
        `pnpm run dev:api` from the repo root). If it's not, the CLI
        exits 2 with a clear message — just tell the user.
        """,
    )


# ───────────────────────────────────────────────────────────────────
# Install / uninstall implementations
# ───────────────────────────────────────────────────────────────────


def _install(
    install_dir: Path,
    repo_root: Path,
    api_base: str,
    force: bool,
) -> int:
    del force  # kept for future "skip if newer" semantics
    skill_dir = install_dir / SKILL_NAME

    wagent_path = _resolve_wagent_binary(repo_root)

    skill_dir.mkdir(parents=True, exist_ok=True)
    run_sh = skill_dir / "run.sh"
    skill_md = skill_dir / "SKILL.md"

    run_sh.write_text(_render_run_sh(wagent_path, repo_root))
    current_mode = run_sh.stat().st_mode
    run_sh.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    skill_md.write_text(_render_skill_md(run_sh, repo_root, api_base))

    print(f"Installed skill '{SKILL_NAME}' → {skill_dir}")
    print(f"  SKILL.md: {skill_md}")
    print(f"  run.sh:   {run_sh}")
    print(f"  wagent:   {wagent_path}{' (missing)' if not wagent_path.exists() else ''}")
    print(f"  API base: {api_base}")

    if not wagent_path.exists():
        print(
            "\nWarning: wagent binary missing. From the repo root run "
            "'.venv/bin/pip install -e apps/cli' to install it into the "
            "venv, then re-run 'wagent skill install' to refresh the shim.",
            file=sys.stderr,
        )

    print(
        "\nClaude Code can now invoke the 'verify-scenario' skill from "
        "any directory while the WebAgentFlow API is running.",
    )
    print("Uninstall with: wagent skill uninstall")
    return 0


def _uninstall(install_dir: Path) -> int:
    skill_dir = install_dir / SKILL_NAME
    if not skill_dir.exists():
        print(f"Skill '{SKILL_NAME}' is not installed at {skill_dir} — nothing to do.")
        return 0

    # Only remove files we own. Refuse to delete a dir we don't
    # recognise — if the operator has written custom files under
    # ~/.claude/skills/verify-scenario/ we shouldn't clobber them.
    expected = {"SKILL.md", "run.sh"}
    present = {p.name for p in skill_dir.iterdir()}
    unexpected = present - expected
    if unexpected:
        print(
            f"Skill dir contains unexpected files ({sorted(unexpected)}); "
            f"refusing to remove. Delete manually: {skill_dir}",
            file=sys.stderr,
        )
        return 2

    for name in expected:
        target = skill_dir / name
        if target.exists():
            target.unlink()
    skill_dir.rmdir()
    print(f"Uninstalled skill '{SKILL_NAME}' from {skill_dir}")
    return 0


# ───────────────────────────────────────────────────────────────────
# Subcommand wiring (called by wagent.main)
# ───────────────────────────────────────────────────────────────────


def configure_install_parser(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--dest",
        type=Path,
        default=DEFAULT_INSTALL_DIR,
        help=f"Claude Code skills root (default {DEFAULT_INSTALL_DIR}).",
    )
    parser.add_argument(
        "--api-base",
        default=os.environ.get("WBAF_API_BASE", "http://localhost:8001"),
        help=(
            "API base URL recorded in SKILL.md for the operator's "
            "reference. CLI defaults to the same via $WBAF_API_BASE."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files (install is idempotent anyway).",
    )


def configure_uninstall_parser(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--dest",
        type=Path,
        default=DEFAULT_INSTALL_DIR,
        help=f"Claude Code skills root (default {DEFAULT_INSTALL_DIR}).",
    )


def run_install(args: argparse.Namespace) -> int:
    return _install(
        install_dir=args.dest,
        repo_root=_repo_root(),
        api_base=args.api_base,
        force=args.force,
    )


def run_uninstall(args: argparse.Namespace) -> int:
    return _uninstall(install_dir=args.dest)
