#!/usr/bin/env python3
"""install_skill — materialize WebAgentFlow's verify-scenario skill into
Claude Code's skill directory.

Run from the repo root:

    pnpm run skill:install         # write files into ~/.claude/skills/
    pnpm run skill:uninstall       # remove the skill

The repo itself does NOT ship with a pre-populated ``.claude/skills/``
tree — that directory belongs to each user's Claude Code home and the
installed copy needs to carry the absolute paths of THIS checkout's
Python interpreter + CLI script. Generating at install time keeps a
single source of truth (this script) and lets the same repo be used
from multiple machines or re-installed after moving the checkout.

The install command rewrites the skill files on every run, so
re-running after updating the repo is idempotent and always produces
absolute paths that still point at the right place.
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path
from textwrap import dedent

SKILL_NAME = "verify-scenario"

# Default install target — Claude Code's user-global skill home. The
# alternative (repo-local ``.claude/skills/``) was rejected because
# the operator needs to invoke the skill from other projects too.
DEFAULT_INSTALL_DIR = Path.home() / ".claude" / "skills"

# When generating run.sh we hard-code the venv Python rather than
# ``$(which python)`` because the skill is invoked from Claude Code's
# Bash tool in whatever environment it happens to run — the venv is
# NOT activated there, and ``which python`` might resolve to the
# system Python that doesn't have httpx installed.
DEFAULT_VENV_PYTHON_REL = Path(".venv") / "bin" / "python"


# ───────────────────────────────────────────────────────────────────
# Template for run.sh
# ───────────────────────────────────────────────────────────────────


def _render_run_sh(python_path: Path, cli_path: Path, repo_root: Path) -> str:
    # The heredoc-style template is intentionally tiny — all the real
    # logic lives in the Python CLI. run.sh is just a shim that
    # resolves the right interpreter and forwards arguments.
    return dedent(
        f"""\
        #!/usr/bin/env bash
        # Generated by WebAgentFlow scripts/install_skill.py
        # Re-run ``pnpm run skill:install`` after moving the repo or
        # re-creating the venv — this file hard-codes absolute paths
        # so it can be invoked from any working directory.
        set -euo pipefail

        WBAF_REPO={_shell_quote(str(repo_root))}
        WBAF_PYTHON={_shell_quote(str(python_path))}
        WBAF_CLI={_shell_quote(str(cli_path))}

        if [[ ! -x "$WBAF_PYTHON" ]]; then
          echo "verify-scenario: Python interpreter missing at $WBAF_PYTHON" >&2
          echo "  Re-create the venv, then re-run 'pnpm run skill:install' from $WBAF_REPO" >&2
          exit 2
        fi
        if [[ ! -f "$WBAF_CLI" ]]; then
          echo "verify-scenario: CLI script missing at $WBAF_CLI" >&2
          echo "  Did the repo move? Re-run 'pnpm run skill:install' from $WBAF_REPO" >&2
          exit 2
        fi

        exec "$WBAF_PYTHON" "$WBAF_CLI" "$@"
        """,
    )


def _shell_quote(value: str) -> str:
    """Minimal POSIX-shell quoting for a single argument."""
    if value and all(
        c.isalnum() or c in "-_./:@=" for c in value
    ):
        return value
    escaped = value.replace("'", "'\\''")
    return f"'{escaped}'"


# ───────────────────────────────────────────────────────────────────
# Template for SKILL.md
# ───────────────────────────────────────────────────────────────────


def _render_skill_md(run_sh: Path, repo_root: Path, api_base: str) -> str:
    # This is the contract Claude Code's skill loader reads. The
    # reporting rules here match the CLAUDE.md execution-boundary
    # section — they must stay in sync.
    return dedent(
        f"""\
        ---
        name: {SKILL_NAME}
        description: >
          Run a WebAgentFlow autonomous exploration (spec-driven or
          ad-hoc URL) and return the project-internal Supervisor
          Agent's verdict and scorecard for analysis. The AI coding
          agent invokes this skill instead of running explorations
          itself.
        ---

        # verify-scenario

        Runs one autonomous exploration against a web page via the
        running WebAgentFlow API and prints the result JSON. The AI
        coding agent (you, Claude Code) invokes this skill when the
        user asks to verify a scenario, run a spec, check a workflow,
        or otherwise exercise the WebAgentFlow engine end-to-end.

        This skill was installed from `{repo_root}` — re-run
        `pnpm run skill:install` from that checkout after a git pull
        so the pinned Python / CLI paths stay current.

        ## When to invoke

        Use this skill when the user's request implies a live run:
        "跑一下 X", "verify scenario Y", "check the users fixture",
        etc. Do NOT use this skill for tasks that don't need a real
        browser run:

        - Inspecting source code → use `Read` / `Grep`
        - Running unit tests → use pytest directly
        - Dry-running ideas without execution → discuss without
          invoking the skill

        ## How to invoke

        Call the shim with Bash. Pick one of the two shapes:

            # Spec-driven (the common case)
            {run_sh} --spec-id <spec> --scenario <scenario>

            # Ad-hoc URL
            {run_sh} --url <url>

        Useful arguments (full list via `{run_sh} --help`):

        - `--spec-id login --scenario valid_credentials` — run a
          persisted spec + scenario; URL and fill_values / toggle_values
          hydrate from the spec automatically.
        - `--url http://localhost:5175/users` — ad-hoc run.
        - `--fill-values '{{"username":"admin"}}'` — override text
          inputs (JSON object, or `@path.json`).
        - `--toggle-values '{{"status":"active"}}'` — override radio /
          checkbox (JSON object, or `@path.json`).
        - `--full` — emit full snapshot (page_analysis + all steps).
          Default is a trimmed summary; the full form is usually too
          large to read in one go. Prefer following the `history_url`
          for deep inspection.
        - `--pretty` — indent the JSON for human reading.
        - `--api-base http://host:port` — point at a non-default API.

        ## Output contract

        - **stdout**: exactly one JSON object with `run_id`, `verdict`,
          `summary`, `final_url`, `supervisor`, `scorecard`, and
          `history_url`. Safe to parse directly.
        - **stderr**: a one-line banner (`✓/✗ verdict — scorecard`) and
          any error text. Ignore when parsing stdout.
        - **exit 0**: verdict == `success`.
        - **exit 1**: verdict in {{`partial_success`, `failure`, `uncertain`}}.
        - **exit 2**: CLI / network / spec error (the run did not happen).

        ## Reporting contract — MUST follow

        When reporting results back to the user, you MUST:

        1. Include `supervisor.verdict` and `supervisor.summary`
           verbatim — do not paraphrase the Supervisor Agent.
        2. Include the 5 scorecard scores:
           `element_recognition`, `action_coverage`, `verdict_accuracy`,
           `distraction_avoidance`, `supervisor_agreement`. Cite the
           actual numbers.
        3. Include the `history_url` so the user can open the detail
           page in their browser.
        4. If the verdict is not `success`, read the step log +
           `supervisor.anomalies` + `supervisor.suggestions` and offer
           a concrete next step (e.g. "the radio selector didn't
           discriminate by value — would you like me to inspect the
           planner's matcher?").

        You MUST NOT:
        - Summarize as "passed" / "failed" without citing the verdict
          and score values from this run.
        - Fabricate verdicts or claim a run succeeded when the exit
          code was non-zero.
        - Re-run the skill in a loop to average results — each run
          costs real Playwright time + an LLM supervisor call.

        ## Prerequisites

        The WebAgentFlow API must be running at `{api_base}` (default
        `pnpm run dev:api` from the repo root). If it's not, the CLI
        exits 2 with a clear message — just tell the user.
        """,
    )


# ───────────────────────────────────────────────────────────────────
# Install / uninstall
# ───────────────────────────────────────────────────────────────────


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _resolve_python(repo_root: Path) -> Path:
    """Best-effort resolve the Python interpreter the skill should use.

    Priority:
      1. $WBAF_PYTHON env var (explicit override)
      2. <repo>/.venv/bin/python (standard dev setup)
      3. sys.executable (fallback — only useful if the installer runs
         inside the venv already)

    The install DOESN'T fail when the venv is missing; it records the
    path anyway and warns. The shim itself fails fast at invocation
    time with a clear error, so missing venv is a recoverable state.
    """
    env_override = os.environ.get("WBAF_PYTHON")
    if env_override:
        return Path(env_override)
    venv_python = repo_root / DEFAULT_VENV_PYTHON_REL
    if venv_python.exists():
        return venv_python
    return Path(sys.executable)


def _resolve_cli(repo_root: Path) -> Path:
    return repo_root / "apps" / "cli" / "verify_scenario.py"


def _install(
    install_dir: Path,
    repo_root: Path,
    api_base: str,
    force: bool,
) -> int:
    skill_dir = install_dir / SKILL_NAME
    if skill_dir.exists() and not force:
        # Idempotent install — always overwrites. --force is only for
        # future "skip if newer" semantics; today it's a no-op flag
        # we keep for compatibility with an eventual update-in-place
        # check. Not prompting the operator here because install is
        # driven from pnpm and should be deterministic.
        pass

    python_path = _resolve_python(repo_root)
    cli_path = _resolve_cli(repo_root)

    skill_dir.mkdir(parents=True, exist_ok=True)
    run_sh = skill_dir / "run.sh"
    skill_md = skill_dir / "SKILL.md"

    run_sh.write_text(_render_run_sh(python_path, cli_path, repo_root))
    current_mode = run_sh.stat().st_mode
    run_sh.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    skill_md.write_text(_render_skill_md(run_sh, repo_root, api_base))

    print(f"Installed skill '{SKILL_NAME}' → {skill_dir}")
    print(f"  SKILL.md: {skill_md}")
    print(f"  run.sh:   {run_sh}")
    print(f"  Python:   {python_path}{' (missing)' if not python_path.exists() else ''}")
    print(f"  CLI:      {cli_path}{' (missing)' if not cli_path.exists() else ''}")
    print(f"  API base: {api_base}")

    if not python_path.exists():
        print(
            "\nWarning: Python interpreter doesn't exist yet. Run "
            "`python3 -m venv .venv && .venv/bin/pip install -e './apps/api[dev]'` "
            "then re-run 'pnpm run skill:install'.",
            file=sys.stderr,
        )
    if not cli_path.exists():
        print(
            "\nWarning: CLI script missing. The repo layout may have "
            "changed; re-run install from the current checkout.",
            file=sys.stderr,
        )

    print(
        "\nClaude Code can now invoke the 'verify-scenario' skill from "
        "any directory while the WebAgentFlow API is running.",
    )
    print(
        "Uninstall with: pnpm run skill:uninstall",
    )
    return 0


def _uninstall(install_dir: Path) -> int:
    skill_dir = install_dir / SKILL_NAME
    if not skill_dir.exists():
        print(f"Skill '{SKILL_NAME}' is not installed at {skill_dir} — nothing to do.")
        return 0

    # Only remove files we own. Refuse to delete a dir we don't
    # recognise — if the operator has written custom files under
    # ~/.claude/skills/verify-scenario/ we shouldn't clobber them.
    expected = {"SKILL.md", "run.sh"}
    present = {p.name for p in skill_dir.iterdir()}
    unexpected = present - expected
    if unexpected:
        print(
            f"Skill dir contains unexpected files ({sorted(unexpected)}); "
            f"refusing to remove. Delete manually: {skill_dir}",
            file=sys.stderr,
        )
        return 2

    for name in expected:
        target = skill_dir / name
        if target.exists():
            target.unlink()
    skill_dir.rmdir()
    print(f"Uninstalled skill '{SKILL_NAME}' from {skill_dir}")
    return 0


# ───────────────────────────────────────────────────────────────────
# CLI
# ───────────────────────────────────────────────────────────────────


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="install_skill",
        description=(
            "Install or uninstall WebAgentFlow's verify-scenario skill "
            "in Claude Code's skill directory."
        ),
    )
    sub = p.add_subparsers(dest="command", required=True)

    install = sub.add_parser("install", help="Write skill files.")
    install.add_argument(
        "--dest",
        type=Path,
        default=DEFAULT_INSTALL_DIR,
        help=f"Claude Code skills root (default {DEFAULT_INSTALL_DIR}).",
    )
    install.add_argument(
        "--api-base",
        default=os.environ.get("WBAF_API_BASE", "http://localhost:8001"),
        help=(
            "API base URL recorded in SKILL.md for the operator's "
            "reference. CLI defaults to the same via $WBAF_API_BASE."
        ),
    )
    install.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files (install is idempotent anyway).",
    )

    uninstall = sub.add_parser("uninstall", help="Remove skill files.")
    uninstall.add_argument(
        "--dest",
        type=Path,
        default=DEFAULT_INSTALL_DIR,
        help=f"Claude Code skills root (default {DEFAULT_INSTALL_DIR}).",
    )

    return p


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    if args.command == "install":
        return _install(
            install_dir=args.dest,
            repo_root=_repo_root(),
            api_base=args.api_base,
            force=args.force,
        )
    if args.command == "uninstall":
        return _uninstall(install_dir=args.dest)
    parser.error(f"Unknown command: {args.command}")
    return 2


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
